name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Executa sempre que você atualizar a branch main

# Permissões necessárias para o GitHub Actions buildar e postar no Pages
permissions:
  contents: read
  pages: write
  id-token: write

environment:
  name: github-pages
  url: ${{ steps.deployment.outputs.page_url }}

jobs:
  build:
    name: Build Astro Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4
        
      - name: Install, lint and build your site
        uses: withastro/action@v3
        # O Astro Action detecta automaticamente o NPM e faz o build seguro

  deploy:
    name: Deploy to Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4